"""init

Revision ID: 1506ff029224
Revises:
Create Date: 2025-05-10 10:08:23.861191

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1506ff029224"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_mcmerchant",
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("merchant_id", sa.String(), nullable=False),
        sa.Column("store_name", sa.String(), nullable=True),
        sa.Column("id", sa.String(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_api_mcmerchant_created_at"), "api_mcmerchant", ["created_at"], unique=False)
    op.create_table(
        "api_merchantproducttrack",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("sku", sa.String(), nullable=False),
        sa.Column("master_sku", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("master_title", sa.String(), nullable=False),
        sa.Column("shop_link", sa.String(), nullable=False),
        sa.Column("available", sa.Boolean(), nullable=False),
        sa.Column("model", sa.String(), nullable=True),
        sa.Column("brand", sa.String(), nullable=True),
        sa.Column("vertical_category", sa.String(), nullable=True),
        sa.Column("master_category", sa.String(), nullable=True),
        sa.Column("min_price", sa.Integer(), nullable=True),
        sa.Column("max_price", sa.Integer(), nullable=True),
        sa.Column("images", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("any_pickup", sa.Boolean(), nullable=True),
        sa.Column("any_kaspi_delivery", sa.Boolean(), nullable=True),
        sa.Column("any_kaspi_delivery_local", sa.Boolean(), nullable=True),
        sa.Column("any_kaspi_delivery_express", sa.Boolean(), nullable=True),
        sa.Column("any_merchant_delivery", sa.Boolean(), nullable=True),
        sa.Column("merchant_id", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["api_mcmerchant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_api_merchantproducttrack_created_at"),
        "api_merchantproducttrack",
        ["created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_api_merchantproducttrack_created_at"), table_name="api_merchantproducttrack")
    op.drop_table("api_merchantproducttrack")
    op.drop_index(op.f("ix_api_mcmerchant_created_at"), table_name="api_mcmerchant")
    op.drop_table("api_mcmerchant")
    # ### end Alembic commands ###
