"""5 alter product

Revision ID: 31b9065d681f
Revises: f907248643ce
Create Date: 2025-05-11 15:33:33.362983

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "31b9065d681f"
down_revision: Union[str, None] = "f907248643ce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
