"""6 alter product

Revision ID: 5d35ba77eb06
Revises: 31b9065d681f
Create Date: 2025-05-11 15:35:19.984909

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "5d35ba77eb06"
down_revision: Union[str, None] = "31b9065d681f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
