"""7 offer video

Revision ID: 6ff2ddb86571
Revises: 5d35ba77eb06
Create Date: 2025-05-15 13:05:47.630834

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6ff2ddb86571"
down_revision: Union[str, None] = "5d35ba77eb06"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("api_merchantproducttrack", sa.Column("video", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("api_merchantproducttrack", "video")
    # ### end Alembic commands ###
