"""8 availability

Revision ID: cc56db7b392a
Revises: 6ff2ddb86571
Create Date: 2025-05-27 11:35:24.645737

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cc56db7b392a"
down_revision: Union[str, None] = "6ff2ddb86571"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_merchantproductavailabilitytrack",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("available", sa.String(), nullable=True),
        sa.Column("store_id", sa.String(), nullable=True),
        sa.Column("stock_count", sa.Integer(), nullable=True),
        sa.Column("pre_order", sa.Integer(), nullable=True),
        sa.Column("stock_enabled", sa.Boolean(), nullable=True),
        sa.Column("stock_specified", sa.Boolean(), nullable=True),
        sa.Column("sku", sa.String(), nullable=False),
        sa.Column("merchant_id", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["api_mcmerchant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_api_merchantproductavailabilitytrack_created_at"),
        "api_merchantproductavailabilitytrack",
        ["created_at"],
        unique=False,
    )
    op.add_column("api_merchantproducttrack", sa.Column("availabilities", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("api_merchantproducttrack", "availabilities")
    op.drop_index(
        op.f("ix_api_merchantproductavailabilitytrack_created_at"),
        table_name="api_merchantproductavailabilitytrack",
    )
    op.drop_table("api_merchantproductavailabilitytrack")
    # ### end Alembic commands ###
