"""3 alter product

Revision ID: db74f2dbda84
Revises: e1d81965fbac
Create Date: 2025-05-10 14:21:53.266204

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "db74f2dbda84"
down_revision: Union[str, None] = "e1d81965fbac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("api_merchantproducttrack", sa.Column("kaspi_merchant_id", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("api_merchantproducttrack", "kaspi_merchant_id")
    # ### end Alembic commands ###
