"""2 alter product

Revision ID: e1d81965fbac
Revises: 0307ab11f34d
Create Date: 2025-05-10 14:13:55.612847

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e1d81965fbac"
down_revision: Union[str, None] = "0307ab11f34d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "api_merchantproducttrack",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.String(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "api_merchantproducttrack",
        "updated_at",
        existing_type=sa.String(),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
