"""4 product specifications

Revision ID: f907248643ce
Revises: db74f2dbda84
Create Date: 2025-05-11 15:30:52.355803

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f907248643ce"
down_revision: Union[str, None] = "db74f2dbda84"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_productfeature",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("product_id", sa.String(), nullable=False),
        sa.Column("class_code", sa.String(), nullable=False),
        sa.Column("class_name", sa.String(), nullable=False),
        sa.Column("attribute_code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("mandatory", sa.Boolean(), nullable=True),
        sa.Column("manufacturer_sku", sa.Boolean(), nullable=True),
        sa.Column("use_for_matching", sa.Boolean(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.Column("attribute_type", sa.String(), nullable=True),
        sa.Column("value", sa.JSON(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_api_productfeature_created_at"), "api_productfeature", ["created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_api_productfeature_created_at"), table_name="api_productfeature")
    op.drop_table("api_productfeature")
    # ### end Alembic commands ###
